---
title: 'Warehouse Wars: The Secret Life of Shipment Volumes and Handling Times'
author: "Avery Holloman"
date: "2024-08-11"
output:
  html_document: default
  pdf_document: default
---

```{r}
# Libraries
library(magrittr)
library(caret)
library(ggthemes)
library(earth)
library(car)
library(plotmo)
library(broom)
library(readr)
library(dplyr)
library(ggplot2)
library(vtreat)
library(sjmisc)
```

```{r}
# Anscombe's Quartet custom dataset I created
data(anscombe)
```

```{r}
# I renamed variables to reflect warehouse logistics 
warehouse_data <- anscombe %>%
  rename(
    Handling_Time_A = x1,
    Shipment_Volume_A = y1,
    Handling_Time_B = x2,
    Shipment_Volume_B = y2,
    Handling_Time_C = x3,
    Shipment_Volume_C = y3,
    Handling_Time_D = x4,
    Shipment_Volume_D = y4
  )
```

```{r}
# Next I wanted to calculate the correlations between the data
cor_A <- cor(warehouse_data$Handling_Time_A, warehouse_data$Shipment_Volume_A) # Correlation for Warehouse A
cor_B <- cor(warehouse_data$Handling_Time_B, warehouse_data$Shipment_Volume_B) # Correlation for Warehouse B
```

```{r}
# Plotting Warehouse Logistics Data with custom colors
par(mfrow = c(2, 2)) # 2x2 grid for plots
```

```{r}
# Changed the colors for my plot to blue and orange
point_color <- "blue"
title_color <- "orange"
```

```{r}
#Plotting with Title name and x and y labels
plot(warehouse_data$Handling_Time_A, warehouse_data$Shipment_Volume_A, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
title(main = "Warehouse A", col.main = title_color)

plot(warehouse_data$Handling_Time_B, warehouse_data$Shipment_Volume_B, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
title(main = "Warehouse B", col.main = title_color)

plot(warehouse_data$Handling_Time_C, warehouse_data$Shipment_Volume_C, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
title(main = "Warehouse C", col.main = title_color)

plot(warehouse_data$Handling_Time_D, warehouse_data$Shipment_Volume_D, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
title(main = "Warehouse D", col.main = title_color)
```

```{r}
# Making a few fitted linear models
model_A <- lm(Shipment_Volume_A ~ Handling_Time_A, data = warehouse_data)
model_B <- lm(Shipment_Volume_B ~ Handling_Time_B, data = warehouse_data)
model_C <- lm(Shipment_Volume_C ~ Handling_Time_C, data = warehouse_data)
model_D <- lm(Shipment_Volume_D ~ Handling_Time_D, data = warehouse_data)
```

```{r}
# I was curious to see the statisical summary
summary(model_A)
summary(model_B)
summary(model_C)
summary(model_D)
```

```{r}
# For better clarity I need some regression lines my plots with red
par(mfrow = c(2, 2)) # Reset to 2x2 grid for plots

plot(warehouse_data$Handling_Time_A, warehouse_data$Shipment_Volume_A, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
abline(model_A, col = "red")
title(main = "Warehouse A with Regression Line", col.main = title_color)

plot(warehouse_data$Handling_Time_B, warehouse_data$Shipment_Volume_B, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
abline(model_B, col = "red")
title(main = "Warehouse B with Regression Line", col.main = title_color)

plot(warehouse_data$Handling_Time_C, warehouse_data$Shipment_Volume_C, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
abline(model_C, col = "red")
title(main = "Warehouse C with Regression Line", col.main = title_color)

plot(warehouse_data$Handling_Time_D, warehouse_data$Shipment_Volume_D, 
     xlab = "Handling Time", ylab = "Shipment Volume", col = point_color, pch = 19)
abline(model_D, col = "red")
title(main = "Warehouse D with Regression Line", col.main = title_color)
```


